CREATE TABLE imovel_foto (
    id BIGSERIAL PRIMARY KEY,
    imovel_id BIGINT NOT NULL REFERENCES imovel(id) ON DELETE CASCADE,
    url VARCHAR(500) NOT NULL,
    legenda VARCHAR(255),
    data_upload TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
